# Generated by Django 4.2 on 2023-05-14 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='votes',
        ),
    ]
