# Generated by Django 4.2 on 2023-05-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_upvotes_post_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
